services:
  streetrace-agent:
    container_name: streetrace
    image: streetrace/streetrace:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/streetrace

