services:
  streetrace-agent:
    container_name: streetrace-agent
    image: streetrace-ai/streetrace-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/streetrace

